<html><table>
  <thead>
    <tr>
    <th colspan="2">head1</th>
          <th colspan="2">head1</th>
    </tr>

    <tr>
    <th>subhead</th>
    <th>subhead</th>
    <th>subhead</th>
    <th>subhead</th>
</tr>
  </thead>
  <tbody>
    <tr>  
      <td>data</td> 
      <td>data</td>
      <td>data</td>
      <td>data</td>

    </tr>
     <tr>  
      <td>data</td> 
      <td>data</td>
      <td>data</td>
      <td>data</td>

    </tr>
     <tr>  
      <td>data</td> 
      <td>data</td>
      <td>data</td>
      <td>data</td>

    </tr>
  </tbody>
</table></html>
